server:
  port: 8080

jwt:
  secret: Yesterday-LoveWasSuchEasyGameToP

parse:
  service:
    url: ${PARSER_SERVICE_URL:http://localhost:8001}

# Python Agent 服务地址
agent:
  service:
    url: ${AGENT_SERVICE_URL:http://localhost:8765}

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml   # 复杂 SQL 的 XML 放哪
  type-aliases-package: com.example.backend.entity      # 实体类包路径，XML 里可以简写
  configuration:
    map-underscore-to-camel-case: true             # 自动驼峰转换（create_time -> createTime）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 到控制台
  global-config:
    db-config:
      id-type: auto
#      logic-delete-field: deleted  # 逻辑删除字段（软删除）
#      logic-delete-value: 1
#      logic-not-delete-value: 0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/video_mind?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
      database: 0
      timeout: 5000ms
  threads:
    virtual:
      enabled: true
  server:
    tomcat:
      threads:
        max: 10000
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:admin}
    password: ${SPRING_RABBITMQ_USERNAME:123456}
    listener:
      simple:
        acknowledge-mode: manual #手动ack
        concurrency: 5 #同时消费5条
        max-concurrency: 20
    publisher-confirm-type: correlated
    publisher-returns: true