upstream video-mind-java {
    server video-mind-java:8080;  # Docker DNS 自动解析到n个IP
}

server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /agent/ {
        proxy_pass http://video-mind-java;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /user/ {
        proxy_pass http://video-mind-java;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /internal/ {
        allow 172.16.0.0/12;  # Docker 内网网段
        allow 10.0.0.0/8;
        deny all;
        proxy_pass http://video-mind-java;
    }
}